### ISSUE TITLE
navi-scripts build is throwing an error message

### ISSUE THREAD

**Issue by github003** [frontarm/create-react-blog#25]
If I run the command "npm run build" it seems to be failing on the "navi-scripts build" step - 

navi-scripts: Using config at /private/tmp/react-blog/navi.config.js
[ohshit] An error occured while building your app
Couldn't find window.NaviScripts - did you call register()?
Error: Couldn't find window.NaviScripts - did you call register()?
    at crawl (/private/tmp/react-blog/node_modules/navi-scripts/lib/crawl.js:22:15)
    at build (/private/tmp/react-blog/node_modules/navi-scripts/lib/build.js:9:32)
    at Command.<anonymous> (/private/tmp/react-blog/node_modules/navi-scripts/bin/navi-scripts.js:89:7)

**Comment by kkacquah** [comment]
I have the same issue with navi-scripts build.

**Comment by minaiism** [comment]
Having the same issue here.
